# ============================================================================
# AWS 用設定
# ============================================================================

Host ec2-jqit-dev
  HostName 54.148.157.219
  User ec2-user
  IdentityFile ~/.ssh/infra-ec2-key.pem
  IdentitiesOnly yes

Host ec2-jqit-dev-tokyo
  HostName 54.65.96.84
  User ec2-user
  IdentityFile ~/.ssh/infra-ec2-tokyo-key.pem
  IdentitiesOnly yes

Host ec2-jqit-prod
  HostName 52.193.211.225
  User ec2-user
  IdentityFile ~/.ssh/kintai-system-production.pem
  IdentitiesOnly yes