# ============================================================================
# AWS 用設定
# ============================================================================

Host ec2-jqit-dev
  HostName 54.148.157.219
  User ec2-user
  IdentityFile ~/.ssh/infra-ec2-key.pem
  IdentitiesOnly yes

Host ec2-jqit-dev-tokyo
  HostName 54.65.96.84
  User ec2-user
  IdentityFile ~/.ssh/infra-ec2-tokyo-key.pem
  IdentitiesOnly yes

Host ec2-tokyo
  HostName 52.192.35.208
  User ec2-user
  IdentityFile ~/.ssh/YUKI_ONO
  IdentitiesOnly yes
  LocalForward 4444 127.0.0.1:14444
  ServerAliveInterval 60
  ServerAliveCountMax 3
  ProxyJump tunnel
